config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  match "/help", to: "home#help", via: [:get], as: 'help'

  resources :comments

  # ----- ADMINISTRATION -----

  resources :tickets do
    patch :close
    patch :open
    resources :comments do
      collection do
        get 'about'
      end
    end
  end


  resources :contacts do
    get :autocomplete_client_name, :on => :collection
    resources :comments do
      collection do
        get 'about'
      end
    end
  end
  match '/contacts/:id/view', to: 'contacts#view', via: [:patch, :get], as: 'view_contact'

  resources :bills do
    get :autocomplete_client_name, :on => :collection
    resources :comments do
      collection do
        get 'about'
      end
    end
  end

  resources :clients do
    get :autocomplete_contact_name, :on => :collection
    resources :comments do
      collection do
        get 'about'
      end
    end
  end

  # ----- DASHBOARDS -----
  match "/users/dashboard", to: 'home#user_dashboard', via: [:get], as: 'users_dashboard'
  match "/users", to: redirect('/users/dashboard'), via: [:get]
  devise_for :users

  match "/admins/dashboard", to: 'home#admin_dashboard', via: [:get], as: 'admins_dashboard'
  match "/admins", to: redirect('/admins/dashboard'), via: [:get]
  match "/admins/export", to: "home#export", via: [:get], as: 'admins_export'
  devise_for :admins

  # ----- CLIENTS -----
  resources :client_tickets, path: '/client/tickets' do
    patch :close
    patch :open
    resources :comments do
      collection do
        get 'about', to: 'comments#about_client'
      end
    end
  end
  resources :client_bills, path: '/client/bills'

end

app/controllers/client_tickets_controller.rb
class ClientTicketsController < ApplicationController
  include CommentableForm

  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :set_ticket_custom_route, only: [:close, :open, :respond]
  before_action :looks_ticket, only: [:show, :edit, :update, :close, :open]
  before_action :authenticate_user!

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = current_user.tickets.order('state DESC')
  end

  def close
    respond_to do |format|
      if @ticket.close
        @ticket.update(admin_view_at: Time.now) # add comment ?
        format.html { redirect_to client_ticket_url(@ticket), notice: 'Ticket was successfully closed.' }
        format.json { render :show, status: :ok, location: client_tickets_url(@ticket) }
      else
        format.html { redirect_to client_ticket_url(@ticket), alert: 'The ticket is already close' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def open
    respond_to do |format|
      if @ticket.open
        @ticket.update(admin_view_at: nil) # add comment ?
        format.html { redirect_to client_ticket_url(@ticket), notice: 'Ticket was successfully reopened.' }
        format.json { render :show, status: :ok, location: client_tickets_url(@ticket) }
      else
        format.html { redirect_to client_ticket_url(@ticket), alert: 'The ticket is already open' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    prepare_comment_for @ticket
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.creator = current_user

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to client_ticket_url(@ticket), notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: client_tickets_url(@ticket) }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: client_tickets_url(@ticket) }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # # DELETE /tickets/1
  # # DELETE /tickets/1.json
  # def destroy
  #   @ticket.destroy
  #   respond_to do |format|
  #     format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    @ticket = Ticket.find_by(id: params[:id], creator: current_user)
    @ticket
  end

  # TODO: remove
  def set_ticket_custom_route
    params[:id] = params[:client_ticket_id]
    set_ticket
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    params.require(:ticket).permit(:title, :description, :state)
  end

  def looks_ticket
    @ticket.set_view_by('User')
  end

end

app/views/client_tickets/_form.html.slim
= form_for @ticket, url: @ticket.id ? client_ticket_path(@ticket) : client_tickets_path do |f|
  - if @ticket.errors.any?
    #error_explanation
      h2 = "#{pluralize(@ticket.errors.count, "error")} prohibited this ticket from being saved:"
      ul
        - @ticket.errors.full_messages.each do |message|
          li = message

  .form-group
    .field
      = f.label :title, class: "sr-only"
      = f.text_field :title, class: "form-control", placeholder: "#{t('.title')}"
  .form-group
    .field
      = f.label :description, class: "sr-only"
      = f.text_area :description, class: "form-control", size: "100x8", placeholder: "#{t('.description')}"
  / display the choice to close only if 'respond to'
  - if @head
    .form-group
      .field
        = f.label t('.state')
        = f.select :state, ["open", "close"], {}, class: "form-control"
  .actions = f.submit class: "btn btn-default"

app/views/client_tickets/edit.html.slim
h1.page-header = t(".page.title")

== render 'form'

= link_to t('show'), client_ticket_path(@ticket), class: 'btn btn-sm btn-default'
= link_to t('back'), client_tickets_path, class: 'btn btn-sm btn-default'

app/views/client_tickets/index.html.slim
h1.page-header = t ".page.title"

table.table.table-condensed
  thead
    tr
      th ID
      th = t ".title"
      th = t ".description"
      th = t ".state"
      th = t ".last_update"
      th = t ".last_response"
      th
      th
      th

  tbody
    - @tickets.each do |ticket|
      tr class="#{ticket.creator_view_at.nil? ? 'bg-warning' : ''}"
        td = link_to("##{ticket.id}", client_ticket_path(ticket))
        td = link_to ticket.title, client_ticket_path(ticket)
        td = ticket.short_description
        - if ticket.state == Ticket::CLOSE
          td.bg-danger = t ".states.close"
        - else
          td.bg-success = t ".states.open"
        td = ticket.updated_at.to_s(:long)
        td = ticket.comments.empty? ? "never" : distance_of_time_in_words_to_now(ticket.comments.first.updated_at)
        td = link_to (t "show"), ticket
        td = link_to (t "edit"), edit_client_ticket_path(ticket)
        - if ticket.open?
          td = link_to (t "close"), client_ticket_close_path(ticket), data: {:confirm => 'Are you sure?'}, :method => :patch
        - elsif ticket.close?
          td = link_to (t "reopen"), client_ticket_open_path(ticket), data: {:confirm => 'Are you sure?'}, :method => :patch

br

= link_to (t "new"), new_client_ticket_path, class: 'btn btn-sm btn-default'

app/views/client_tickets/new.html.slim
h1 = @head ? t("client_tickets.response.page.title") : t(".page.title")

== render 'form'

= link_to t('back'), client_tickets_path, class: 'btn btn-sm btn-default'

app/views/client_tickets/show.html.slim
h1.page-header = "Ticket: #{@ticket.title}"

p
  strong
    | Id: #
    = @ticket.id
p
  strong = t ".title"
  |: 
  = link_to @ticket.title, client_ticket_path(@ticket)

p
  strong = t ".state"
  |: 
  - if @ticket.state == Ticket::CLOSE
    td.bg-danger = t ".states.close"
  - else
    td.bg-success = t ".states.open"

p
  strong = t ".creator"
  |: 
  span.ticket-creator = link_to_creator @ticket
p
  strong = t ".title"
  |: 
  = @ticket.title
p
  strong = t ".description"
  |: 
  .container-fluid.ticket-description
    = descriptionize @ticket.description

== render partial: "/comments/thread", locals: {commentable: @ticket, type: 'user'}

br

- if @ticket.open?
  = link_to (t 'close'), client_ticket_close_path(@ticket), method: :patch, class: 'btn btn-sm btn-success'
- else
  = link_to (t 'reopen'), client_ticket_open_path(@ticket), method: :patch, class: 'btn btn-sm btn-danger'
= link_to (t 'edit'), edit_client_ticket_path(@ticket), class: 'btn btn-sm btn-default'
= link_to (t 'back'), client_tickets_path, class: 'btn btn-sm btn-default'