config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  match "/help", to: "home#help", via: [:get], as: 'help'

  resources :comments

  # ----- ADMINISTRATION -----

  resources :tickets do
    patch :close
    patch :open
    resources :comments do
      collection do
        get 'about'
      end
    end
  end


  resources :contacts do
    get :autocomplete_client_name, :on => :collection
    resources :comments do
      collection do
        get 'about'
      end
    end
  end
  match '/contacts/:id/view', to: 'contacts#view', via: [:patch, :get], as: 'view_contact'

  resources :bills do
    get :autocomplete_client_name, :on => :collection
    resources :comments do
      collection do
        get 'about'
      end
    end
  end

  resources :clients do
    get :autocomplete_contact_name, :on => :collection
    resources :comments do
      collection do
        get 'about'
      end
    end
  end

  # ----- DASHBOARDS -----
  match "/users/dashboard", to: 'home#user_dashboard', via: [:get], as: 'users_dashboard'
  match "/users", to: redirect('/users/dashboard'), via: [:get]
  devise_for :users

  match "/admins/dashboard", to: 'home#admin_dashboard', via: [:get], as: 'admins_dashboard'
  match "/admins", to: redirect('/admins/dashboard'), via: [:get]
  match "/admins/export", to: "home#export", via: [:get], as: 'admins_export'
  devise_for :admins

  # ----- CLIENTS -----
  resources :client_tickets, path: '/client/tickets' do
    patch :close
    patch :open
    resources :comments do
      collection do
        get 'about', to: 'comments#about_client'
      end
    end
  end
  resources :client_bills, path: '/client/bills'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_admin!, only: [:admin_dashboard, :export]
  before_action :authenticate_user!, only: [:user_dashboard]

  def user_dashboard
    @retard_bills = current_user.bills.retard.count
    @advanced_bills = current_user.bills.advanced.count
    @next_bills = current_user.bills.next.count
    @old_bills = current_user.bills.old.count
    @bills_count = current_user.bills.count
    @ticket_closed = current_user.tickets.close.count
    @ticket_opened = current_user.tickets.open.count
    @ticket_waiting = current_user.tickets_unview.count
  end

  def admin_dashboard
    @clients_count = Client.count
    @contacts_count = Contact.count
    @no_client_contacts_count = (Client.all.pluck(:id) - Contact.all.pluck(:client_id).uniq).size
    @retard_bills = Bill.retard.count
    @advanced_bills = Bill.advanced.count
    @next_bills = Bill.next.count
    @old_bills = Bill.old.count
    @bills_count = Bill.count
    @ticket_closed = Ticket.close.count
    @ticket_opened = Ticket.open.count
    @ticket_waiting = current_admin.tickets_unview.count
  end

  def export
    redirect_to "/admins/export.json" if params[:format] != "json"
    @clients = Client.all
    @contacts = Contact.all
    @bills = Bill.all
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin_dashboard.html.slim
h1.page-header = t ".title"

.row.placeholders
  .col-xs-6.col-sm-2.placeholder
    = link_to clients_url do
      = image_tag "icone_client.png", alt: "image clients", class: "img-responsive", size: "128x128"
    h4 Clients
    span.text-muted = "Count: #{@clients_count}"
    br

  .col-xs-6.col-sm-2.placeholder
    = link_to contacts_url do
      = image_tag "icone_contact.png", alt: "image contact", class: "img-responsive", size: "128x128"
    h4 Contacts
    span.text-muted = "Count: #{@contacts_count}"
    br
    span.text-muted = "Client with no contacts: #{@no_client_contacts_count}"
    br

  .col-xs-6.col-sm-2.placeholder
    = link_to bills_url do
      = image_tag "icone_bill.png", alt: "image bills", class: "img-responsive", size: "128x128"
    h4 Bills
    span.text-muted = "Retard bills: #{@retard_bills}"
    br
    span.text-muted = "Advanced bills: #{@advanced_bills}"
    br
    span.text-muted = "Next bills: #{@retard_bills}"
    br
    span.text-muted = "Old bills: #{@old_bills}"
    br
    span.text-muted = "Total Bills: #{@bills_count}"
    br

  .col-xs-6.col-sm-2.placeholder
    = link_to tickets_url do
      = image_tag "icone_ticket.png", alt: "image tickets", class: "img-responsive", size: "128x128"
    h4 Tickets
    span.text-muted = "Closed tickets: #{@ticket_closed}"
    br
    span.text-muted = "Opened tickets: #{@ticket_opened}"
    br
    span.text-muted = "Waiting tickets: #{@ticket_waiting}"
    br

  .col-xs-6.col-sm-2.placeholder
    = link_to admins_export_url do
      = image_tag "icone_export.png", alt: "image export", class: "img-responsive", size: "128x128"
    h4
      abbr[title="This option only export the clients, contacts, and bills, without comments etc. If you want to export the complete database, use the native feature of your ORDBMS."] Export
    span.text-muted = "Clients: #{@clients_count}"
    br
    span.text-muted = "Contacts: #{@contacts_count}"
    br
    span.text-muted = "Bills: #{@bills_count}"
    br

  / here, add a wonderful statistic graph with js

app/views/home/help.html.slim
h1.page-header Help

- if user_signed_in?
  .panel.panel-primary
    .panel-heading
      .panel-title Client
    .panel-body
      p
        | Wecome to the Morning Peak CRM. 
        | This is an open source web application, designed for you, client of a provider, and your creditor. 
        | The application is compatible on Desktop, Tablet, and Mobiles. 
      h3 On Desktop
      p
        | With a large screen, you will be able to use the left sidebar panel. It allowes you to access to your 
        | dashboard (click on 'User'). You have also a link to the bills you due to your provider, and a links to the tickets, 
        | used to make easier the contact and conversation with him.
      h3 On Tablet and Mobile
      p
        | With Tablets and Mobiles, you cannot see the sidebar panel. Instead, you will have an access to your dashboard, 
        | by using the square button on the top right. 
        br
        | On the dashboard, you will see how many Bills you have (due, passed, ...) and the same for your tickets.

- if admin_signed_in?
  .panel.panel-danger
    .panel-heading
      .panel-title Admin
    .panel-body
      p
        | You can access to the list of your clients, the contacts for each clients, 
        | the bills your clients due to you and also the tickets to communicate with them. 

- if not user_signed_in? and not admin_signed_in?
  .panel.panel-primary
    .panel-heading
      .panel-title Connection
    .panel-body
      p
        | To use this application, you have to sign in as a Client or Administrator with your créditentials.
        br
        = link_to "Sign in as User", new_user_session_path
        br
        | If you are an administrator, use this link instead
        br
        = link_to "Sign in as Admin", new_admin_session_path
        br

p
  | You can also contact the administrator, via the 
  = link_to "developpers on the website", "https://gitlab.com/poulet_a/MorningPeak/issues"
  br
  | Please, don't forget to be explicit and to write carefully. 
  | It the request is too much broad, then it will not be handled. 

app/views/home/index.html.slim
.container
  .row
    .space-client.col-xs-4
      .panel.panel-success
        .panel-heading
          h3 = t "home.user_dashboard.title"
        .panel-body
          - if user_signed_in?
            = link_to t(".links.logout"), destroy_user_session_path, method: :delete
          - else
            = link_to t(".links.login"), new_user_session_path
    .space-admin.col-xs-4
      .panel.panel-danger
        .panel-heading
          h3 = t("home.admin_dashboard.title")
        .panel-body
          - if admin_signed_in?
            = link_to t(".links.logout"), destroy_admin_session_path, method: :delete
          - else
            = link_to t(".links.login"), new_admin_session_path

app/views/home/user_dashboard.html.slim
h1.page-header = t ".title"

.row.placeholders
  .col-xs-6.col-sm-3.placeholder
    = link_to client_bills_url do
      = image_tag "icone_bill.png", alt: "image bills", class: "img-responsive", size: "128x128"
    h4 = t "home.dashboard.bills"
    span.text-muted = "#{t 'home.dashboard.retard_bills'}: #{@retard_bills}"
    br
    span.text-muted = "#{t 'home.dashboard.advanced_bills'}: #{@advanced_bills}"
    br
    span.text-muted = "#{t 'home.dashboard.next_bills'}: #{@retard_bills}"
    br
    span.text-muted = "#{t 'home.dashboard.old_bills'}: #{@old_bills}"
    br
    span.text-muted = "#{t 'home.dashboard.total_bills'}: #{@bills_count}"
    br

  .col-xs-6.col-sm-3.placeholder
    = link_to client_tickets_url do
      = image_tag "icone_ticket.png", alt: "image tickets", class: "img-responsive", size: "128x128"
    h4 = t "home.dashboard.tickets"
    span.text-muted = "#{t 'home.dashboard.closed_tickets'}: #{@ticket_closed}"
    br
    span.text-muted = "#{t 'home.dashboard.opened_tickets'}: #{@ticket_opened}"
    br
    span.text-muted = "#{t 'home.dashboard.waiting_tickets'}: #{@ticket_waiting}"
    br