config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  match "/help", to: "home#help", via: [:get], as: 'help'

  resources :comments

  # ----- ADMINISTRATION -----

  resources :tickets do
    patch :close
    patch :open
    resources :comments do
      collection do
        get 'about'
      end
    end
  end


  resources :contacts do
    get :autocomplete_client_name, :on => :collection
    resources :comments do
      collection do
        get 'about'
      end
    end
  end
  match '/contacts/:id/view', to: 'contacts#view', via: [:patch, :get], as: 'view_contact'

  resources :bills do
    get :autocomplete_client_name, :on => :collection
    resources :comments do
      collection do
        get 'about'
      end
    end
  end

  resources :clients do
    get :autocomplete_contact_name, :on => :collection
    resources :comments do
      collection do
        get 'about'
      end
    end
  end

  # ----- DASHBOARDS -----
  match "/users/dashboard", to: 'home#user_dashboard', via: [:get], as: 'users_dashboard'
  match "/users", to: redirect('/users/dashboard'), via: [:get]
  devise_for :users

  match "/admins/dashboard", to: 'home#admin_dashboard', via: [:get], as: 'admins_dashboard'
  match "/admins", to: redirect('/admins/dashboard'), via: [:get]
  match "/admins/export", to: "home#export", via: [:get], as: 'admins_export'
  devise_for :admins

  # ----- CLIENTS -----
  resources :client_tickets, path: '/client/tickets' do
    patch :close
    patch :open
    resources :comments do
      collection do
        get 'about', to: 'comments#about_client'
      end
    end
  end
  resources :client_bills, path: '/client/bills'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  acts_as_commentable
  belongs_to :client

  delegate :name, to: :client, prefix: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  include CommentableForm

  autocomplete :client, :name

  before_action :set_contact, only: [:show, :edit, :update, :destroy, :view]
  before_action :authenticate_admin!

  # PATCH /view/1
  def view
    @contact.update(view_at: Time.now)
    render json: @contact, status: :ok
  end

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    prepare_comment_for @contact
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:client_id, :name, :phone, :email, :note, :region, :department, :postal_code, :address)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.slim
= form_for @contact do |f|
  - if @contact.errors.any?
    #error_explanation
      h2 = "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      ul
        - @contact.errors.full_messages.each do |message|
          li = message

  .form-horizontal
    .form-group
      .field
        = f.autocomplete_field :client, autocomplete_client_name_contacts_path, :id_element => '#contact_client_id', class: "form-control", placeholder: "Client Name"
        = f.label :client_id, class: "sr-only"
        = f.text_field :client_id, class: "form-control sr-only", placeholder: "Client ID"
  .form-inline
    .form-group
      .field
        = f.label :name, class: "sr-only"
        = f.text_field :name, class: "form-control", placeholder: "Name"
    .form-group
      .field
        = f.label :phone, class: "sr-only"
        = f.text_field :phone, class: "form-control", placeholder: "Phone"
    .form-group
      .field
        = f.label :email, class: "sr-only"
        = f.text_field :email, class: "form-control", placeholder: "Email"
  .form-inline
    .form-group
      .field
        = f.label :region, class: "sr-only"
        = f.text_field :region, class: "form-control", placeholder: "Region"
    .form-group
      .field
        = f.label :department, class: "sr-only"
        = f.text_field :department, class: "form-control", placeholder: "Department"
    .form-group
      .field
        = f.label :postal_code, class: "sr-only"
        = f.text_field :postal_code, class: "form-control", placeholder: "Postal Code"
  .form-horizontal
    .form-group
      .field
        = f.label :address, class: "sr-only"
        = f.text_area :address, class: "form-control", placeholder: "Address"
    .form-group
      .field
        = f.label :note, class: "sr-only"
        = f.text_area :note, class: "form-control", placeholder: "Note"
    .form-group
      .field
        = f.label :view_at, class: "sr-only"
        = f.text_field :view_at, class: "form-control form-date", placeholder: "View at"
  .actions = f.submit class: "btn btn-success"

app/views/contacts/edit.html.slim
h1.page-header Editing contact

== render 'form'

= link_to 'Show', @contact
'|
= link_to 'Back', contacts_path

app/views/contacts/index.html.slim
h1.page-header Listing contacts

table.table.table-condensed.
  thead
    tr
      td ID
      th Client
      th Name
      th Phone
      th Email
      th Note
      th Postal code
      th Last view
      th
      th
      th
      th

  tbody
    - @contacts.each do |contact|
      tr
        td = contact.id
        td = link_to contact.client.name, contact.client
        td = link_to contact.name, contact
        td = contact.phone
        td = contact.email
        td = contact.note
        td = contact.postal_code
        td.contact-value-view_at
          = contact.view_at
        td.contact-link-view_at
          = link_to 'View today!', view_contact_path(contact), method: :patch, remote: true
        td = link_to 'Show', contact
        td = link_to 'Edit', edit_contact_path(contact)
        td = link_to 'Destroy', contact, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Contact', new_contact_path, class: 'btn btn-sm btn-default'

app/views/contacts/new.html.slim
h1.page-header New contact

== render 'form'

= link_to 'Back', contacts_path

app/views/contacts/show.html.slim
h1.page-header Show contact

p
  strong Client:
  = link_to @contact.client.name, @contact.client
p
  strong Name:
  = @contact.name
p
  strong Phone:
  = @contact.phone
p
  strong Email:
  = @contact.email
p
  strong View at:
  = @contact.view_at
p
  strong Note:
  = @contact.note
p
  strong Region:
  = @contact.region
p
  strong Department:
  = @contact.department
p
  strong Postal code:
  = @contact.postal_code
p
  strong Address:
  = @contact.address

= link_to 'Edit', edit_contact_path(@contact), class: 'btn btn-sm btn-default'
= link_to 'Back', contacts_path, class: 'btn btn-sm btn-default'

#comments.container-fluid
  h2.page-header Comments
  = render partial: "/comments/about", locals: {commentable: @contact}
  = render partial: "/comments/form"