config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  match "/help", to: "home#help", via: [:get], as: 'help'

  resources :comments

  # ----- ADMINISTRATION -----

  resources :tickets do
    patch :close
    patch :open
    resources :comments do
      collection do
        get 'about'
      end
    end
  end


  resources :contacts do
    get :autocomplete_client_name, :on => :collection
    resources :comments do
      collection do
        get 'about'
      end
    end
  end
  match '/contacts/:id/view', to: 'contacts#view', via: [:patch, :get], as: 'view_contact'

  resources :bills do
    get :autocomplete_client_name, :on => :collection
    resources :comments do
      collection do
        get 'about'
      end
    end
  end

  resources :clients do
    get :autocomplete_contact_name, :on => :collection
    resources :comments do
      collection do
        get 'about'
      end
    end
  end

  # ----- DASHBOARDS -----
  match "/users/dashboard", to: 'home#user_dashboard', via: [:get], as: 'users_dashboard'
  match "/users", to: redirect('/users/dashboard'), via: [:get]
  devise_for :users

  match "/admins/dashboard", to: 'home#admin_dashboard', via: [:get], as: 'admins_dashboard'
  match "/admins", to: redirect('/admins/dashboard'), via: [:get]
  match "/admins/export", to: "home#export", via: [:get], as: 'admins_export'
  devise_for :admins

  # ----- CLIENTS -----
  resources :client_tickets, path: '/client/tickets' do
    patch :close
    patch :open
    resources :comments do
      collection do
        get 'about', to: 'comments#about_client'
      end
    end
  end
  resources :client_bills, path: '/client/bills'

end

app/views/layouts/_infos.html.slim
#infos
  - if alert
    #alert.alert.bg-danger
      span.glyphicon.glyphicon-exclamation-sign aria-hidden="true"
      span.sr-only Error:
      = " #{alert}"
  - if notice
    #notice.alert.bg-warning
      span.glyphicon.glyphicon-info-sign aria-hidden="true"
      span.sr-only Error:
      = " #{notice}"

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    #navbar-title.navbar-header
      button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      .navbar-brand
        = link_to application_title, root_url

    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li = link_to t(".user_dashboard"), users_dashboard_url
        - if admin_signed_in?
          li = link_to t(".admin_dashboard"), admins_dashboard_url
        - if user_signed_in?
          li = link_to "#{current_user.name} #{t '.logout'}", destroy_user_session_path, method: :delete
        - if admin_signed_in?
          li = link_to "#{current_admin.email} #{t '.logout'}", destroy_admin_session_path, method: :delete
        li = link_to "Help", help_url

app/views/layouts/_sidebar.html.slim
.col-sm-3.col-md-2.sidebar
  / User side
  - if user_signed_in?
    ul.nav.nav-sidebar
      li.active
        = link_to users_dashboard_url do
          = t ".user.user"
          span.sr-only (current)
      li = link_to client_bills_url do
        = t ".user.bills_due"
        .badge = user_bills_count_due
      li = link_to client_tickets_url do
        = t ".user.tickets"
        .badge = user_tickets_unview_count

  / Admin side
  - if admin_signed_in?
    - if user_signed_in?
      br
    ul.nav.nav-sidebar
      li.active
        = link_to admins_dashboard_url do
          = t(".admin.admin")
          span.sr-only (current)
      li = link_to t(".admin.clients"), clients_url
      li = link_to t(".admin.contacts"), contacts_url
      li = link_to t( ".admin.bills"), bills_url
      li = link_to tickets_url do
        = t ".admin.tickets"
        .badge = admin_tickets_unview_count

app/views/layouts/application.html.slim
doctype html
html
  head
    title = application_title
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = render partial: "/layouts/navbar"

    .container-fluid
      .row
        = render partial: "/layouts/sidebar"

        #main.main.col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main

          = render partial: "/layouts/infos"
          #yield.yield
            = yield